language: java

notifications:
  on_success: never
  on_failure: never

addons:
  sonarcloud:
    organization: "diogopontes-github"
    token:
      secure: $SONAR_TOKEN
script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar 